### ISSUE TITLE
Tons of dead links on the sapphic.moe contact page

### ISSUE THREAD

**Issue by xzi** [SapphicMoe/sapphic.moe#24]
Hello! I noticed there are a ton of dead links on https://sapphic.moe/contact . Many links on the page link to https://solstice.tf which is now offline. I figured I would let you know so you can fix it. Site is very pretty otherwise. Glhf

e: edited to clarify

**Comment by SapphicMoe** [comment]
Fixed! Sorry for the very late response. Thank you for reporting.
